// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	models "github.com/nurhalimkoinworks/go-utest/models"
	mock "github.com/stretchr/testify/mock"

	serror "github.com/koinworks/asgard-heimdal/libs/serror"
)

// ILoanRepository is an autogenerated mock type for the ILoanRepository type
type ILoanRepository struct {
	mock.Mock
}

// Get provides a mock function with given fields: args
func (_m *ILoanRepository) Get(args models.GetLoanArgs) (models.Loan, serror.SError) {
	ret := _m.Called(args)

	var r0 models.Loan
	if rf, ok := ret.Get(0).(func(models.GetLoanArgs) models.Loan); ok {
		r0 = rf(args)
	} else {
		r0 = ret.Get(0).(models.Loan)
	}

	var r1 serror.SError
	if rf, ok := ret.Get(1).(func(models.GetLoanArgs) serror.SError); ok {
		r1 = rf(args)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(serror.SError)
		}
	}

	return r0, r1
}
