// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	models "github.com/nurhalimkoinworks/go-utest/models"
	mock "github.com/stretchr/testify/mock"

	serror "github.com/koinworks/asgard-heimdal/libs/serror"
)

// IRepaymentRepository is an autogenerated mock type for the IRepaymentRepository type
type IRepaymentRepository struct {
	mock.Mock
}

// GetScheduleList provides a mock function with given fields: args
func (_m *IRepaymentRepository) GetScheduleList(args models.GetScheduleListArgs) ([]models.RepaymentSchedule, serror.SError) {
	ret := _m.Called(args)

	var r0 []models.RepaymentSchedule
	if rf, ok := ret.Get(0).(func(models.GetScheduleListArgs) []models.RepaymentSchedule); ok {
		r0 = rf(args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.RepaymentSchedule)
		}
	}

	var r1 serror.SError
	if rf, ok := ret.Get(1).(func(models.GetScheduleListArgs) serror.SError); ok {
		r1 = rf(args)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(serror.SError)
		}
	}

	return r0, r1
}
