name: Go
on:
  push:
    branches:
      - gitaction-2.0
  pull_request:
    branches:
      - gitaction-2.0
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.12.9
        uses: actions/setup-go@v2
        with:
          go-version: 1.12.9
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: git config --global url."https://nurhalimkoinworks:${726b23f4331833435eb341f41109a6b456127c2d}@github.com".insteadOf "github.com/koinworks/asgard-heimdal"

      - name: Get dependencies
        run: go mod tidy

      - name: Test
        run: go test ./service/...